[package]
name = "topk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
topk-protos = { path = "../topk-protos" }
tonic = { version = "0.12.3" }
tokio = { version = "1.35", features = ["full"] }
anyhow = { version = "1.0.77" }
thiserror = { version = "1.0.65" }
tracing = { version = "0.1.40" }
serde_json = { version = "1.0" }
