[package]
edition = "2021"
name = "topk-js"
description = "TopK JavaScript SDK with TypeScript support"
version = "0.0.0"
repository = "https://github.com/fafolabs/topk-sdk"
homepage = "https://topk.io"
documentation = "https://docs.topk.io"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
