name: Test SDKs

on:
  pull_request:
    types: [labeled]

jobs:
  python:
    runs-on: [earthly-satellite#bob-the-builder-amd64]
    if: ${{ github.event.label.name == 'ready' }}
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
    steps:
      - uses: actions/checkout@v2

      - name: Python tests
        run: earthly --secret TOPK_API_KEY +test-py
